name: Mirror EmulatorJS Assets to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'EmulatorJS version to mirror'
        required: true
        type: string

jobs:
  mirror:
    runs-on: ubuntu-latest
    environment:
        name: cloudflare-r2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install p7zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Download EmulatorJS assets
        run: |
          mkdir -p ${{ inputs.version }}
          curl -L "https://github.com/EmulatorJS/EmulatorJS/releases/download/v${{ inputs.version }}/${{ inputs.version }}.7z" -o "${{ inputs.version }}.7z"
          7z x "${{ inputs.version }}.7z" -o${{ inputs.version }}/
          rm "${{ inputs.version }}.7z"

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.S3_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws configure set endpoint_url ${{ secrets.S3_ENDPOINT }}

      - name: Sync to S3
        run: |
          aws s3 sync ${{ inputs.version }}/ s3://${{ secrets.S3_BUCKET }}/${{ inputs.version }}/ \
            --cache-control "public, max-age=31536000, immutable" \
            --delete \
            --endpoint-url ${{ secrets.S3_ENDPOINT }}

      - name: Cleanup
        run: |
          rm -rf ${{ inputs.version }}
